"""Centralized application catalog for installer + launcher workflows."""

from __future__ import annotations

from copy import deepcopy

SYSTEM_TO_PLATFORM = {
    "Linux": "linux",
    "Darwin": "darwin",
    "Windows": "windows",
}


APP_CATALOG = [
    {
        "app_id": "ollama",
        "display_name": "Ollama",
        "desc": "Local LLM runner for Llama, Mistral, Gemma and more.",
        "category": "local_ai",
        "supported_platforms": ["linux", "darwin", "windows"],
        "install_type": "shell",
        "homepage_url": "https://ollama.com",
        "download_url": "https://raw.githubusercontent.com/ollama/ollama/main/scripts/install.sh",
        "fallback_urls": ["https://ollama.com/install.sh", "https://github.com/ollama/ollama/releases/latest"],
        "validation_strategy": "binary_and_health",
        "launch_strategy": "service",
        "binary_name": "ollama",
        "install_dir_hint": "system PATH",
        "known_limitations": "Requires Linux service management for background mode.",
        "checksum_url": None,
        "release_discovery_strategy": {
            "type": "stable_endpoint"
        },
        "launch_type": "service",
        "launch_command_linux": ["ollama", "serve"],
        "launch_command_windows": ["ollama", "serve"],
        "post_install_validation_command": ["ollama", "--version"],
        "requires_terminal": True,
        "requires_service": True,
        "requires_elevated_permissions": False,
        "linux_download": "https://raw.githubusercontent.com/ollama/ollama/main/scripts/install.sh",
        "darwin_download": "https://ollama.com/download/Ollama-darwin.zip",
        "windows_download": "https://ollama.com/download/OllamaSetup.exe",
        "linux_install_type": "shell",
        "darwin_install_type": "zip",
        "windows_install_type": "exe",
    },
    {
        "app_id": "lmstudio",
        "display_name": "LM Studio",
        "desc": "GUI desktop app for running local AI models.",
        "category": "local_ai",
        "supported_platforms": ["linux", "darwin", "windows"],
        "install_type": "appimage",
        "homepage_url": "https://lmstudio.ai",
        "download_url": "https://lmstudio.ai/download",
        "fallback_urls": ["https://installers.lmstudio.ai/linux/x64/"],
        "validation_strategy": "binary_version",
        "launch_strategy": "appimage",
        "binary_name": "LM-Studio",
        "install_dir_hint": "~/.local/bin",
        "known_limitations": "Release asset names may change by architecture.",
        "checksum_url": None,
        "release_discovery_strategy": {
            "type": "lmstudio_linux_appimage",
            "discovery_page": "https://lmstudio.ai/download"
        },
        "validate_download": "appimage_elf",
        "validate_install": "binary_version_command",
        "launch_type": "appimage",
        "launch_command_linux": ["LM-Studio"],
        "launch_command_windows": ["LM Studio"],
        "start_command": ["LM-Studio"],
        "post_install_validation_command": ["LM-Studio", "--version"],
        "requires_terminal": False,
        "requires_service": False,
        "requires_elevated_permissions": False,
    },
    {
        "app_id": "gpt4all",
        "display_name": "GPT4All",
        "desc": "Privacy-first local AI chat.",
        "category": "local_ai",
        "supported_platforms": ["linux", "darwin", "windows"],
        "install_type": "run",
        "homepage_url": "https://gpt4all.io",
        "download_url": "https://gpt4all.io/installers/gpt4all-installer-linux.run",
        "fallback_urls": ["https://gpt4all.io/installers/"],
        "validation_strategy": "binary_version",
        "launch_strategy": "binary",
        "binary_name": "gpt4all",
        "install_dir_hint": "~/.local/share/gpt4all",
        "known_limitations": "Linux installer may require interactive fallback.",
        "checksum_url": None,
        "release_discovery_strategy": {"type": "stable_endpoint"},
        "validate_download": "run_script",
        "validate_install": "binary_version_command",
        "launch_type": "binary",
        "launch_command_linux": ["gpt4all"],
        "launch_command_windows": ["gpt4all"],
        "start_command": ["gpt4all"],
        "post_install_validation_command": ["gpt4all", "--version"],
        "requires_terminal": False,
        "requires_service": False,
        "requires_elevated_permissions": False,
    },
    {
        "app_id": "jan",
        "display_name": "Jan",
        "desc": "Open-source local ChatGPT alternative.",
        "category": "local_ai",
        "supported_platforms": ["linux", "darwin", "windows"],
        "install_type": "appimage",
        "homepage_url": "https://github.com/janhq/jan",
        "download_url": "https://app.jan.ai/download/latest/linux-amd64-appimage",
        "fallback_urls": [],
        "validation_strategy": "binary_version",
        "launch_strategy": "appimage",
        "binary_name": "jan",
        "install_dir_hint": "~/.local/bin",
        "known_limitations": "Asset naming differs across release versions.",
        "checksum_url": None,
        "release_discovery_strategy": {
            "type": "stable_endpoint"
        },
        "validate_download": "appimage_elf",
        "validate_install": "binary_version_command",
        "launch_type": "appimage",
        "launch_command_linux": ["jan"],
        "launch_command_windows": ["jan"],
        "start_command": ["jan"],
        "post_install_validation_command": ["jan", "--version"],
        "requires_terminal": False,
        "requires_service": False,
        "requires_elevated_permissions": False,
    },
    {
        "app_id": "anythingllm",
        "display_name": "AnythingLLM",
        "desc": "All-in-one RAG/agent desktop app.",
        "category": "local_ai",
        "supported_platforms": ["linux", "darwin", "windows"],
        "install_type": "appimage",
        "homepage_url": "https://docs.anythingllm.com/installation-desktop/linux",
        "download_url": "https://cdn.anythingllm.com/latest/AnythingLLMDesktop.AppImage",
        "fallback_urls": [],
        "validation_strategy": "binary_version",
        "launch_strategy": "appimage",
        "binary_name": "AnythingLLMDesktop",
        "install_dir_hint": "~/.local/bin",
        "known_limitations": "Desktop build asset names can vary.",
        "checksum_url": None,
        "release_discovery_strategy": {"type": "stable_endpoint"},
        "validate_download": "appimage_elf",
        "validate_install": "binary_version_command",
        "launch_type": "appimage",
        "launch_command_linux": ["AnythingLLMDesktop"],
        "launch_command_windows": ["AnythingLLMDesktop"],
        "start_command": ["AnythingLLMDesktop"],
        "post_install_validation_command": ["AnythingLLMDesktop", "--version"],
        "requires_terminal": False,
        "requires_service": False,
        "requires_elevated_permissions": False,
    },
    {
        "app_id": "msty",
        "display_name": "Msty",
        "desc": "Universal AI desktop client.",
        "category": "local_ai",
        "supported_platforms": ["linux", "darwin", "windows"],
        "install_type": "appimage",
        "homepage_url": "https://msty.app",
        "download_url": "",
        "fallback_urls": [],
        "validation_strategy": "binary_version",
        "launch_strategy": "appimage",
        "binary_name": "Msty",
        "install_dir_hint": "~/.local/bin",
        "known_limitations": "Vendor CDN occasionally rotates paths.",
        "checksum_url": None,
        "release_discovery_strategy": {"type": "unverified_linux_asset"},
        "linux_auto_install_verified": False,
        "validate_download": "appimage_elf",
        "validate_install": "binary_version_command",
        "launch_type": "appimage",
        "launch_command_linux": ["Msty"],
        "launch_command_windows": ["Msty"],
        "start_command": ["Msty"],
        "post_install_validation_command": ["Msty", "--version"],
        "requires_terminal": False,
        "requires_service": False,
        "requires_elevated_permissions": False,
    },
    {
        "app_id": "open_webui",
        "display_name": "Open WebUI",
        "desc": "Self-hosted AI frontend for local/cloud models.",
        "category": "local_ai",
        "supported_platforms": ["linux", "darwin", "windows"],
        "install_type": "pip",
        "homepage_url": "https://github.com/open-webui/open-webui",
        "download_url": "https://github.com/open-webui/open-webui/releases/latest",
        "fallback_urls": ["https://pypi.org/project/open-webui/"],
        "validation_strategy": "cli_help",
        "launch_strategy": "cli",
        "binary_name": "open-webui",
        "install_dir_hint": "python environment",
        "known_limitations": "Prefer pip install on Linux over desktop wrappers.",
        "checksum_url": None,
        "release_discovery_strategy": {
            "type": "pypi_package",
            "package": "open-webui",
        },
        "validate_download": "pip_wheel",
        "validate_install": "cli_help",
        "launch_type": "cli",
        "launch_command_linux": ["open-webui", "serve"],
        "launch_command_windows": ["open-webui", "serve"],
        "start_command": ["open-webui", "serve"],
        "post_install_validation_command": ["open-webui", "--help"],
        "requires_terminal": True,
        "requires_service": False,
        "requires_elevated_permissions": False,
    },
    {
        "app_id": "opera",
        "display_name": "Opera One",
        "desc": "Browser with AI assistant (Aria).",
        "category": "browsers",
        "supported_platforms": ["linux", "darwin", "windows"],
        "install_type": "deb",
        "homepage_url": "https://www.opera.com",
        "download_url": "https://download3.operacdn.com/pub/opera/desktop/",
        "fallback_urls": ["https://www.opera.com/download"],
        "validation_strategy": "binary_version",
        "launch_strategy": "binary",
        "binary_name": "opera",
        "install_dir_hint": "/usr/bin/opera",
        "known_limitations": "Vendor versioned path may change.",
        "checksum_url": None,
        "release_discovery_strategy": {"type": "stable_endpoint"},
        "launch_type": "binary",
        "launch_command_linux": ["opera"],
        "launch_command_windows": ["opera"],
        "post_install_validation_command": ["opera", "--version"],
        "requires_terminal": False,
        "requires_service": False,
        "requires_elevated_permissions": False,
        "linux_download": "https://download3.operacdn.com/pub/opera/desktop/latest/linux/opera-stable_latest_amd64.deb",
    },
    {
        "app_id": "perplexity_app",
        "display_name": "Perplexity Desktop",
        "desc": "Perplexity desktop client.",
        "category": "browsers",
        "supported_platforms": ["darwin", "windows"],
        "install_type": "manual",
        "homepage_url": "https://www.perplexity.ai",
        "download_url": "https://www.perplexity.ai/download",
        "fallback_urls": [],
        "validation_strategy": "manual",
        "launch_strategy": "manual",
        "binary_name": "",
        "install_dir_hint": "N/A on Linux",
        "known_limitations": "No official Linux desktop build.",
        "checksum_url": None,
        "release_discovery_strategy": {"type": "release_page"},
        "launch_type": "manual",
        "launch_command_linux": [],
        "launch_command_windows": ["Perplexity"],
        "post_install_validation_command": [],
        "requires_terminal": False,
        "requires_service": False,
        "requires_elevated_permissions": False,
    },
    {
        "app_id": "dia",
        "display_name": "Dia Browser",
        "desc": "AI-native browser by The Browser Company.",
        "category": "browsers",
        "supported_platforms": ["darwin", "windows"],
        "install_type": "manual",
        "homepage_url": "https://www.diabrowser.com",
        "download_url": "https://www.diabrowser.com/download",
        "fallback_urls": [],
        "validation_strategy": "manual",
        "launch_strategy": "manual",
        "binary_name": "",
        "install_dir_hint": "N/A on Linux",
        "known_limitations": "No official Linux build at this time.",
        "checksum_url": None,
        "release_discovery_strategy": {"type": "release_page"},
        "launch_type": "manual",
        "launch_command_linux": [],
        "launch_command_windows": ["Dia"],
        "post_install_validation_command": [],
        "requires_terminal": False,
        "requires_service": False,
        "requires_elevated_permissions": False,
    },
    {
        "app_id": "edge_copilot",
        "display_name": "Microsoft Edge / Copilot",
        "desc": "Microsoft Edge with Copilot sidebar.",
        "category": "browsers",
        "supported_platforms": ["linux", "darwin", "windows"],
        "install_type": "deb",
        "homepage_url": "https://www.microsoft.com/edge",
        "download_url": "https://packages.microsoft.com/repos/edge/pool/main/m/microsoft-edge-stable/",
        "fallback_urls": ["https://www.microsoft.com/edge/download"],
        "validation_strategy": "binary_version",
        "launch_strategy": "binary",
        "binary_name": "microsoft-edge",
        "install_dir_hint": "/usr/bin/microsoft-edge",
        "known_limitations": "Linux package URLs are architecture-specific.",
        "checksum_url": None,
        "release_discovery_strategy": {"type": "stable_endpoint"},
        "launch_type": "binary",
        "launch_command_linux": ["microsoft-edge"],
        "launch_command_windows": ["msedge"],
        "post_install_validation_command": ["microsoft-edge", "--version"],
        "requires_terminal": False,
        "requires_service": False,
        "requires_elevated_permissions": False,
        "linux_download": "https://packages.microsoft.com/repos/edge/pool/main/m/microsoft-edge-stable/microsoft-edge-stable_current_amd64.deb",
    },
    {
        "app_id": "brave",
        "display_name": "Brave Browser / Leo",
        "desc": "Brave browser with Leo assistant.",
        "category": "browsers",
        "supported_platforms": ["linux", "darwin", "windows"],
        "install_type": "apt-repo",
        "homepage_url": "https://brave.com",
        "download_url": "https://brave.com/linux/",
        "fallback_urls": ["https://github.com/brave/brave-browser/releases/latest"],
        "validation_strategy": "binary_version",
        "launch_strategy": "binary",
        "binary_name": "brave-browser",
        "install_dir_hint": "/usr/bin/brave-browser",
        "known_limitations": "GitHub assets can change names.",
        "checksum_url": None,
        "release_discovery_strategy": {
            "type": "github_latest_asset",
            "repo": "brave/brave-browser",
            "asset_patterns": {
                "linux": [".*amd64.*\\.deb$", ".*x86_64.*\\.deb$"],
                "darwin": [".*(arm64|universal).*(\\.dmg|\\.pkg)$"],
                "windows": [".*(Setup|Installer).*x64.*\\.exe$"],
            },
        },
        "launch_type": "binary",
        "launch_command_linux": ["brave-browser"],
        "launch_command_windows": ["brave"],
        "post_install_validation_command": ["brave-browser", "--version"],
        "requires_terminal": False,
        "requires_service": False,
        "requires_elevated_permissions": False,
    },
    {
        "app_id": "cursor",
        "display_name": "Cursor",
        "desc": "AI-first code editor.",
        "category": "productivity",
        "supported_platforms": ["linux", "darwin", "windows"],
        "install_type": "appimage",
        "homepage_url": "https://cursor.com",
        "download_url": "https://downloader.cursor.sh/linux/appImage/x64",
        "fallback_urls": ["https://www.cursor.com/downloads"],
        "validation_strategy": "binary_version",
        "launch_strategy": "appimage",
        "binary_name": "cursor",
        "install_dir_hint": "~/.local/bin",
        "known_limitations": "Direct URL can redirect by release channel.",
        "checksum_url": None,
        "release_discovery_strategy": {"type": "vendor_redirect"},
        "launch_type": "appimage",
        "launch_command_linux": ["cursor"],
        "launch_command_windows": ["Cursor"],
        "post_install_validation_command": ["cursor", "--version"],
        "requires_terminal": False,
        "requires_service": False,
        "requires_elevated_permissions": False,
    },
    {
        "app_id": "windsurf",
        "display_name": "Windsurf",
        "desc": "Agentic AI IDE by Codeium.",
        "category": "productivity",
        "supported_platforms": ["linux", "darwin", "windows"],
        "install_type": "appimage",
        "homepage_url": "https://codeium.com/windsurf",
        "download_url": "https://windsurf-stable.codeiumdata.com/wVxQEIWkwPUEAGf3/windsurf/latest/Windsurf.AppImage",
        "fallback_urls": ["https://codeium.com/windsurf/download"],
        "validation_strategy": "binary_version",
        "launch_strategy": "appimage",
        "binary_name": "Windsurf",
        "install_dir_hint": "~/.local/bin",
        "known_limitations": "Vendor CDN path can rotate.",
        "checksum_url": None,
        "release_discovery_strategy": {"type": "stable_endpoint"},
        "launch_type": "appimage",
        "launch_command_linux": ["Windsurf"],
        "launch_command_windows": ["Windsurf"],
        "post_install_validation_command": ["Windsurf", "--version"],
        "requires_terminal": False,
        "requires_service": False,
        "requires_elevated_permissions": False,
    },
    {
        "app_id": "notion",
        "display_name": "Notion",
        "desc": "Notion desktop application.",
        "category": "productivity",
        "supported_platforms": ["darwin", "windows"],
        "install_type": "manual",
        "homepage_url": "https://www.notion.so/desktop",
        "download_url": "https://www.notion.so/desktop",
        "fallback_urls": [],
        "validation_strategy": "manual",
        "launch_strategy": "manual",
        "binary_name": "",
        "install_dir_hint": "No official Linux desktop build.",
        "known_limitations": "Linux desktop app is community-managed only.",
        "checksum_url": None,
        "release_discovery_strategy": {"type": "release_page"},
        "launch_type": "manual",
        "launch_command_linux": [],
        "launch_command_windows": ["Notion"],
        "post_install_validation_command": [],
        "requires_terminal": False,
        "requires_service": False,
        "requires_elevated_permissions": False,
    },
    {
        "app_id": "trae",
        "display_name": "Trae",
        "desc": "AI-native IDE by ByteDance.",
        "category": "productivity",
        "supported_platforms": ["linux", "darwin", "windows"],
        "install_type": "appimage",
        "homepage_url": "https://trae.ai",
        "download_url": "https://download.trae.ai/linux/latest/Trae.AppImage",
        "fallback_urls": [],
        "validation_strategy": "binary_version",
        "launch_strategy": "appimage",
        "binary_name": "Trae",
        "install_dir_hint": "~/.local/bin",
        "known_limitations": "Vendor latest links may rotate.",
        "checksum_url": None,
        "release_discovery_strategy": {"type": "stable_endpoint"},
        "launch_type": "appimage",
        "launch_command_linux": ["Trae"],
        "launch_command_windows": ["Trae"],
        "post_install_validation_command": ["Trae", "--version"],
        "requires_terminal": False,
        "requires_service": False,
        "requires_elevated_permissions": False,
    },
    {
        "app_id": "zed",
        "display_name": "Zed",
        "desc": "Collaborative AI editor.",
        "category": "productivity",
        "supported_platforms": ["linux", "darwin", "windows"],
        "install_type": "tar.gz",
        "homepage_url": "https://zed.dev",
        "download_url": "https://zed.dev/download",
        "fallback_urls": ["https://zed.dev/releases/preview"],
        "validation_strategy": "binary_version",
        "launch_strategy": "binary",
        "binary_name": "zed",
        "install_dir_hint": "~/.local/share/zed",
        "known_limitations": "Linux package format can vary by channel.",
        "checksum_url": None,
        "release_discovery_strategy": {"type": "vendor_redirect"},
        "launch_type": "binary",
        "launch_command_linux": ["zed"],
        "launch_command_windows": ["Zed"],
        "post_install_validation_command": ["zed", "--version"],
        "requires_terminal": False,
        "requires_service": False,
        "requires_elevated_permissions": False,
    },
    {
        "app_id": "gh_copilot",
        "display_name": "GitHub Copilot CLI",
        "desc": "GitHub CLI with Copilot extension workflows.",
        "category": "productivity",
        "supported_platforms": ["linux", "darwin", "windows"],
        "install_type": "tar.gz",
        "homepage_url": "https://github.com/cli/cli",
        "download_url": "https://github.com/cli/cli/releases/latest",
        "fallback_urls": ["https://cli.github.com/"],
        "validation_strategy": "binary_version",
        "launch_strategy": "cli",
        "binary_name": "gh",
        "install_dir_hint": "~/.local/bin",
        "known_limitations": "Copilot command needs extension auth after install.",
        "checksum_url": "https://github.com/cli/cli/releases/latest",
        "release_discovery_strategy": {
            "type": "github_latest_asset",
            "repo": "cli/cli",
            "asset_patterns": {
                "linux": ["^gh_.*_linux_amd64\\.tar\\.gz$"],
                "darwin": ["^gh_.*_macOS_.*\\.zip$"],
                "windows": ["^gh_.*_windows_amd64\\.zip$"],
            },
        },
        "launch_type": "cli",
        "launch_command_linux": ["gh", "copilot", "--help"],
        "launch_command_windows": ["gh", "copilot", "--help"],
        "post_install_validation_command": ["gh", "--version"],
        "requires_terminal": True,
        "requires_service": False,
        "requires_elevated_permissions": False,
    },
]


def list_apps() -> list[dict]:
    return [deepcopy(app) for app in APP_CATALOG]


def get_app(app_id: str) -> dict | None:
    for app in APP_CATALOG:
        if app["app_id"] == app_id:
            return deepcopy(app)
    return None


def apps_for_category(category: str) -> list[dict]:
    return [deepcopy(a) for a in APP_CATALOG if a.get("category") == category]


def platform_supported(app: dict, platform_name: str) -> bool:
    platform_key = SYSTEM_TO_PLATFORM.get(platform_name, platform_name.lower())
    return platform_key in app.get("supported_platforms", [])


def to_legacy_installer(app: dict, system_name: str) -> dict:
    platform_key = SYSTEM_TO_PLATFORM.get(system_name, system_name.lower())
    url_field = f"{platform_key}_download"
    install_type_field = f"{platform_key}_install_type"
    url = app.get(url_field) or app.get("download_url")
    if platform_key not in app.get("supported_platforms", []):
        url = None
    install_type = app.get(install_type_field) or app.get("install_type")
    return {
        "id": app["app_id"],
        "name": app["display_name"],
        "desc": app.get("desc", ""),
        "urls": {system_name: url},
        "fmt": {system_name: install_type},
    }


def legacy_groups(system_name: str) -> dict:
    by_category = {
        "local_ai": [],
        "browsers": [],
        "productivity": [],
    }
    for app in APP_CATALOG:
        cat = app.get("category", "local_ai")
        by_category.setdefault(cat, []).append(to_legacy_installer(app, system_name))
    return by_category
