"""Scenario schema definitions, templates, and built-in scenario pack."""

from __future__ import annotations

from datetime import datetime, timezone

CATEGORY_ORDER: list[str] = [
    "IDE Assistants",
    "Desktop AI Apps",
    "Browser AI Services",
    "Search-Integrated AI",
    "Local Model Tools",
    "Agent + MCP Workflows",
    "File/Data Transfer Simulations",
    "Cross-App Chained Workflows",
]

RISK_LEVELS = {"low", "medium", "high", "critical"}
SUPPORTED_PLATFORMS = {"linux", "windows", "darwin", "any"}

SCENARIO_FIELDS: list[str] = [
    "id",
    "title",
    "description",
    "category",
    "family",
    "tags",
    "risk_level",
    "platforms",
    "auth_required",
    "prerequisites",
    "steps",
    "assertions",
    "expected_observables",
    "detector_expectations",
    "cleanup_steps",
    "created_date",
    "last_run_date",
    "status",
    "metadata",
]

STEP_TYPE_DEFINITIONS: list[dict] = [
    {
        "type": "install_application",
        "label": "Install application",
        "description": "Install an app by catalog id or display name.",
        "os_support": ["linux", "windows", "darwin"],
        "fields": [
            {"name": "app_name", "label": "Application", "input": "text", "required": True, "placeholder": "vscode, ollama"},
        ],
    },
    {
        "type": "install_browser_extension",
        "label": "Install extension",
        "description": "Install extension for a target app (for example VS Code).",
        "os_support": ["linux", "windows", "darwin"],
        "fields": [
            {"name": "target_app", "label": "Target app", "input": "text", "required": True, "placeholder": "vscode"},
            {"name": "extension_id", "label": "Extension id", "input": "text", "required": True, "placeholder": "GitHub.copilot"},
        ],
    },
    {
        "type": "launch_application",
        "label": "Launch application",
        "description": "Launch installed application.",
        "os_support": ["linux", "windows", "darwin"],
        "fields": [
            {"name": "app_name", "label": "Application", "input": "text", "required": True, "placeholder": "vscode, ollama"},
        ],
    },
    {
        "type": "open_website",
        "label": "Open website",
        "description": "Open URL in Playwright browser context.",
        "os_support": ["linux", "windows", "darwin"],
        "fields": [
            {"name": "url", "label": "URL", "input": "text", "required": True, "placeholder": "https://chatgpt.com"},
            {"name": "requires_capability", "label": "Requires capability", "input": "text", "required": False, "placeholder": "google_ai_mode"},
        ],
    },
    {
        "type": "click_selector",
        "label": "Click selector",
        "description": "Click CSS selector on active page.",
        "os_support": ["linux", "windows", "darwin"],
        "fields": [
            {"name": "selector", "label": "CSS selector", "input": "text", "required": True, "placeholder": "textarea"},
        ],
    },
    {
        "type": "type_text",
        "label": "Type text",
        "description": "Type text into active browser page or desktop input.",
        "os_support": ["linux", "windows", "darwin"],
        "fields": [
            {"name": "text", "label": "Text", "input": "textarea", "required": True},
        ],
    },
    {
        "type": "press_shortcut",
        "label": "Press shortcut",
        "description": "Send keyboard shortcut.",
        "os_support": ["linux", "windows", "darwin"],
        "fields": [
            {"name": "keys", "label": "Shortcut", "input": "text", "required": True, "placeholder": "ctrl+v"},
        ],
    },
    {
        "type": "upload_file",
        "label": "Upload file",
        "description": "Upload sample file in browser file input.",
        "os_support": ["linux", "windows", "darwin"],
        "fields": [
            {"name": "selector", "label": "File input selector", "input": "text", "required": True, "placeholder": "input[type=file]"},
            {"name": "path", "label": "File path", "input": "text", "required": True, "placeholder": "simulator_data/scenarios/samples/sample_brief.txt"},
        ],
    },
    {
        "type": "copy_text",
        "label": "Copy text",
        "description": "Copy explicit text or text from selector into simulated clipboard.",
        "os_support": ["linux", "windows", "darwin"],
        "fields": [
            {"name": "text", "label": "Static text", "input": "textarea", "required": False},
            {"name": "selector", "label": "Source selector", "input": "text", "required": False},
        ],
    },
    {
        "type": "paste_text",
        "label": "Paste text",
        "description": "Paste simulated clipboard into selector or active input.",
        "os_support": ["linux", "windows", "darwin"],
        "fields": [
            {"name": "selector", "label": "Target selector", "input": "text", "required": False, "placeholder": "textarea"},
            {"name": "text", "label": "Override text", "input": "textarea", "required": False},
        ],
    },
    {
        "type": "manual_checkpoint",
        "label": "Manual checkpoint",
        "description": "Pause run for analyst action (for example login or MFA).",
        "os_support": ["linux", "windows", "darwin"],
        "fields": [
            {"name": "instruction", "label": "Instruction", "input": "textarea", "required": True},
            {"name": "timeout_seconds", "label": "Timeout seconds", "input": "number", "required": False, "default": 900},
            {"name": "auto_continue", "label": "Auto-continue", "input": "checkbox", "required": False, "default": False},
        ],
    },
    {
        "type": "capability_check",
        "label": "Capability check",
        "description": "Gate scenario branch on environment capability.",
        "os_support": ["linux", "windows", "darwin"],
        "fields": [
            {"name": "capability", "label": "Capability name", "input": "text", "required": True, "placeholder": "google_ai_mode"},
            {"name": "fail_if_missing", "label": "Fail if missing", "input": "checkbox", "required": False, "default": False},
        ],
    },
    {
        "type": "mcp_install_server",
        "label": "Install MCP server",
        "description": "Install MCP server package.",
        "os_support": ["linux", "windows", "darwin"],
        "fields": [
            {"name": "server_id", "label": "Server id", "input": "text", "required": True, "placeholder": "filesystem"},
        ],
    },
    {
        "type": "mcp_inject_config",
        "label": "Inject MCP config",
        "description": "Inject MCP server config into supported AI client config.",
        "os_support": ["linux", "windows", "darwin"],
        "fields": [
            {"name": "server_ids", "label": "Server ids (comma separated)", "input": "text", "required": True, "placeholder": "filesystem,postgres"},
        ],
    },
    {
        "type": "pull_local_model",
        "label": "Pull local model",
        "description": "Pull local model via Ollama.",
        "os_support": ["linux", "windows", "darwin"],
        "fields": [
            {"name": "model", "label": "Model", "input": "text", "required": True, "placeholder": "llama3.2:1b"},
        ],
    },
    {
        "type": "assert_text_contains",
        "label": "Assert text contains",
        "description": "Assert page body contains expected substring.",
        "os_support": ["linux", "windows", "darwin"],
        "fields": [
            {"name": "expected", "label": "Expected text", "input": "text", "required": True},
        ],
    },
    {
        "type": "assert_clipboard_contains",
        "label": "Assert clipboard contains",
        "description": "Assert clipboard text contains expected value.",
        "os_support": ["linux", "windows", "darwin"],
        "fields": [
            {"name": "expected", "label": "Expected text", "input": "text", "required": True},
        ],
    },
    {
        "type": "capture_screenshot",
        "label": "Capture screenshot",
        "description": "Capture browser screenshot for evidence.",
        "os_support": ["linux", "windows", "darwin"],
        "fields": [
            {"name": "path", "label": "Output path", "input": "text", "required": False, "placeholder": "simulator_data/scenarios/screenshots/scn.png"},
        ],
    },
    {
        "type": "wait",
        "label": "Wait",
        "description": "Wait before next step.",
        "os_support": ["linux", "windows", "darwin"],
        "fields": [
            {"name": "seconds", "label": "Seconds", "input": "number", "required": True, "default": 2},
        ],
    },
    {
        "type": "close_application",
        "label": "Close application",
        "description": "Close managed process or app.",
        "os_support": ["linux", "windows", "darwin"],
        "fields": [
            {"name": "app_name", "label": "Application", "input": "text", "required": True, "placeholder": "vscode, ollama"},
        ],
    },
]

STEP_FIELDS_BY_TYPE = {item["type"]: item["fields"] for item in STEP_TYPE_DEFINITIONS}

SCENARIO_TEMPLATES: list[dict] = [
    {
        "template_id": "template-installation-footprint",
        "scenario_id": "tpl-installation-footprint",
        "title": "Installation footprint test",
        "description": "Validate installer telemetry and artifact placement.",
        "recommended_category": "Desktop AI Apps",
        "recommended_family": "Installation Footprint",
    },
    {
        "template_id": "template-pre-auth-use",
        "scenario_id": "tpl-pre-auth-use",
        "title": "Pre-auth use test",
        "description": "Exercise prompt surfaces before account sign-in.",
        "recommended_category": "IDE Assistants",
        "recommended_family": "Pre-Auth Prompting",
    },
    {
        "template_id": "template-post-auth-use",
        "scenario_id": "tpl-post-auth-use",
        "title": "Post-auth use test",
        "description": "Resume execution after login checkpoint and verify tool usage.",
        "recommended_category": "Desktop AI Apps",
        "recommended_family": "Post-Auth Prompting",
    },
    {
        "template_id": "template-file-upload",
        "scenario_id": "tpl-file-upload",
        "title": "File upload test",
        "description": "Upload sample text/csv/pdf and request summary.",
        "recommended_category": "File/Data Transfer Simulations",
        "recommended_family": "Upload + Summary",
    },
    {
        "template_id": "template-copy-paste-exfil",
        "scenario_id": "tpl-copy-paste-exfil",
        "title": "Copy/paste exfil simulation test",
        "description": "Copy generated output from one app and paste into another app.",
        "recommended_category": "Cross-App Chained Workflows",
        "recommended_family": "Clipboard Relay",
    },
    {
        "template_id": "template-mcp-connector",
        "scenario_id": "tpl-mcp-connector",
        "title": "MCP/tool connector test",
        "description": "Install MCP package, inject config, and verify manual interaction checkpoint.",
        "recommended_category": "Agent + MCP Workflows",
        "recommended_family": "Connector Provisioning",
    },
    {
        "template_id": "template-cross-app-chain",
        "scenario_id": "tpl-cross-app-chain",
        "title": "Multi-step cross-app workflow",
        "description": "Chain browser, desktop assistant, and IDE operations in sequence.",
        "recommended_category": "Cross-App Chained Workflows",
        "recommended_family": "Cross-App Relay",
    },
    {
        "template_id": "template-local-model-only",
        "scenario_id": "tpl-local-model-only",
        "title": "Local-model-only workflow",
        "description": "Install local runtime, pull model, prompt locally, collect observables.",
        "recommended_category": "Local Model Tools",
        "recommended_family": "Offline Local Prompting",
    },
]


def now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def normalize_platforms(platforms: list[str] | str | None) -> list[str]:
    if platforms is None:
        return ["any"]
    if isinstance(platforms, str):
        raw = [platforms]
    else:
        raw = list(platforms)

    normalized = []
    for item in raw:
        val = str(item).strip().lower()
        if val in SUPPORTED_PLATFORMS and val not in normalized:
            normalized.append(val)
    return normalized or ["any"]


def _scenario(
    scenario_id: str,
    title: str,
    description: str,
    category: str,
    family: str,
    tags: list[str],
    risk_level: str,
    platforms: list[str],
    auth_required: bool,
    prerequisites: list[str],
    steps: list[dict],
    assertions: list[str],
    expected_observables: list[str],
    detector_expectations: list[str],
    cleanup_steps: list[str],
    *,
    is_template: bool = False,
) -> dict:
    return {
        "id": scenario_id,
        "title": title,
        "description": description,
        "category": category,
        "family": family,
        "tags": tags,
        "risk_level": risk_level.lower(),
        "platforms": normalize_platforms(platforms),
        "auth_required": bool(auth_required),
        "prerequisites": prerequisites,
        "steps": steps,
        "assertions": assertions,
        "expected_observables": expected_observables,
        "detector_expectations": detector_expectations,
        "cleanup_steps": cleanup_steps,
        "created_date": now_iso(),
        "last_run_date": None,
        "status": "idle",
        "metadata": {
            "source": "built_in",
            "is_template": is_template,
        },
    }


def built_in_scenarios() -> list[dict]:
    starter = [
        _scenario(
            "scn-vscode-copilot-no-login",
            "VS Code + GitHub Copilot prompt surface (no login)",
            "Install VS Code if needed, install Copilot extension, launch prompt surface without signing in.",
            "IDE Assistants",
            "VS Code Extensions",
            ["vscode", "copilot", "pre-auth", "extension"],
            "high",
            ["linux", "windows"],
            False,
            ["Internet access for extension download"],
            [
                {"id": "s1", "type": "install_application", "params": {"app_name": "vscode"}},
                {"id": "s2", "type": "install_browser_extension", "params": {"target_app": "vscode", "extension_id": "GitHub.copilot"}},
                {"id": "s3", "type": "launch_application", "params": {"app_name": "vscode"}},
                {"id": "s4", "type": "manual_checkpoint", "params": {"instruction": "Open Copilot Chat panel and verify pre-auth prompt UI appears.", "timeout_seconds": 900}},
            ],
            ["Prompt UI visible without authenticated completion request"],
            ["code process creation", "extension install telemetry"],
            ["EDR process tree: code -> extension install", "HTTP to VS Code marketplace"],
            ["Close VS Code"],
        ),
        _scenario(
            "scn-vscode-claude-code-no-login",
            "VS Code + Claude Code extension prompt surface (no login)",
            "Install VS Code if needed, install Claude extension, open assistant prompt surface without account login.",
            "IDE Assistants",
            "VS Code Extensions",
            ["vscode", "claude", "pre-auth", "extension"],
            "high",
            ["linux", "windows"],
            False,
            ["Internet access for extension download"],
            [
                {"id": "s1", "type": "install_application", "params": {"app_name": "vscode"}},
                {"id": "s2", "type": "install_browser_extension", "params": {"target_app": "vscode", "extension_id": "anthropic.claude-code"}},
                {"id": "s3", "type": "launch_application", "params": {"app_name": "vscode"}},
                {"id": "s4", "type": "manual_checkpoint", "params": {"instruction": "Open Claude extension panel and verify prompt surface appears before login.", "timeout_seconds": 900}},
            ],
            ["Prompt panel reachable pre-auth"],
            ["extension installation network call", "IDE launch telemetry"],
            ["SIEM package install plus IDE plugin activity"],
            ["Close VS Code"],
        ),
        _scenario(
            "scn-claude-desktop-mcp-login",
            "Claude Desktop login + MCP connector workflow",
            "Install Claude desktop if available, complete login manually, install filesystem MCP server, inject config, then interact with tool.",
            "Agent + MCP Workflows",
            "Connector Provisioning",
            ["claude", "mcp", "post-auth", "filesystem"],
            "critical",
            ["linux", "windows", "darwin"],
            True,
            ["Node/npm/npx recommended", "Claude Desktop installed for real config path"],
            [
                {"id": "s1", "type": "install_application", "params": {"app_name": "claude_desktop"}},
                {"id": "s2", "type": "manual_checkpoint", "params": {"instruction": "Log into Claude Desktop account and keep the app open.", "timeout_seconds": 1200}},
                {"id": "s3", "type": "mcp_install_server", "params": {"server_id": "filesystem"}},
                {"id": "s4", "type": "mcp_inject_config", "params": {"server_ids": "filesystem"}},
                {"id": "s5", "type": "manual_checkpoint", "params": {"instruction": "In Claude Desktop, invoke MCP filesystem tool and run a simple directory listing.", "timeout_seconds": 1200}},
            ],
            ["MCP server installed", "Config file modified", "Manual MCP tool interaction recorded"],
            ["npx process creation", "config file integrity change"],
            ["FIM event for Claude config", "EDR child process from assistant app"],
            ["Restore MCP config if required"],
        ),
        _scenario(
            "scn-google-ai-mode-eligible",
            "Google AI Mode prompt test (gated)",
            "Check Google AI Mode capability and, if eligible, open browser and submit a prompt.",
            "Search-Integrated AI",
            "Google AI Mode",
            ["google", "ai-mode", "browser", "gated"],
            "medium",
            ["linux", "windows", "darwin"],
            False,
            ["Chromium available"],
            [
                {"id": "s1", "type": "capability_check", "params": {"capability": "google_ai_mode", "fail_if_missing": False}},
                {"id": "s2", "type": "open_website", "params": {"url": "https://www.google.com/search?q=ai+mode", "requires_capability": "google_ai_mode"}},
                {"id": "s3", "type": "click_selector", "params": {"selector": "textarea, input[name='q']"}},
                {"id": "s4", "type": "type_text", "params": {"text": "Summarize zero trust controls for data exfiltration."}},
                {"id": "s5", "type": "press_shortcut", "params": {"keys": "enter"}},
            ],
            ["Capability gate evaluated", "Prompt submission attempted when eligible"],
            ["browser DNS/HTTPS telemetry"],
            ["Search-integrated AI traffic in proxy logs"],
            ["Close browser context"],
        ),
        _scenario(
            "scn-perplexity-login-followup",
            "Perplexity login prompt + follow-up",
            "Open browser, pause for login, submit initial prompt and follow-up prompt.",
            "Search-Integrated AI",
            "Perplexity Follow-up",
            ["perplexity", "browser", "follow-up", "auth"],
            "high",
            ["linux", "windows", "darwin"],
            True,
            ["Perplexity account"],
            [
                {"id": "s1", "type": "open_website", "params": {"url": "https://www.perplexity.ai"}},
                {"id": "s2", "type": "manual_checkpoint", "params": {"instruction": "Complete Perplexity login, then resume.", "timeout_seconds": 1200}},
                {"id": "s3", "type": "click_selector", "params": {"selector": "textarea"}},
                {"id": "s4", "type": "type_text", "params": {"text": "Provide a concise DLP policy gap checklist."}},
                {"id": "s5", "type": "press_shortcut", "params": {"keys": "enter"}},
                {"id": "s6", "type": "wait", "params": {"seconds": 4}},
                {"id": "s7", "type": "type_text", "params": {"text": "Now prioritize the top three controls for first quarter rollout."}},
                {"id": "s8", "type": "press_shortcut", "params": {"keys": "enter"}},
            ],
            ["Initial and follow-up prompts submitted"],
            ["session cookies", "prompt traffic", "response render"],
            ["Auth plus AI search usage in web telemetry"],
            ["Close browser context"],
        ),
        _scenario(
            "scn-ollama-local-prompt",
            "Ollama local prompt baseline",
            "Install Ollama, pull small model, submit local prompt, and verify local API response markers.",
            "Local Model Tools",
            "Ollama Baseline",
            ["ollama", "local", "offline", "model-pull"],
            "medium",
            ["linux", "windows", "darwin"],
            False,
            ["Enough disk for model pull"],
            [
                {"id": "s1", "type": "install_application", "params": {"app_name": "ollama"}},
                {"id": "s2", "type": "launch_application", "params": {"app_name": "ollama"}},
                {"id": "s3", "type": "pull_local_model", "params": {"model": "llama3.2:1b"}},
                {"id": "s4", "type": "open_website", "params": {"url": "http://127.0.0.1:11434/api/tags"}},
                {"id": "s5", "type": "assert_text_contains", "params": {"expected": "models"}},
            ],
            ["Local model pull completed", "Local API tags endpoint reachable"],
            ["localhost inference service traffic", "model artifact pull"],
            ["No cloud API calls required for prompt"],
            ["Close Ollama process"],
        ),
        _scenario(
            "scn-browser-output-to-vscode",
            "Browser AI output copied to VS Code",
            "Submit browser AI prompt, copy response text, then paste into VS Code editor.",
            "Cross-App Chained Workflows",
            "Browser-to-IDE",
            ["copy-paste", "browser", "vscode", "exfil"],
            "critical",
            ["linux", "windows"],
            False,
            ["VS Code available", "Browser access to AI site"],
            [
                {"id": "s1", "type": "open_website", "params": {"url": "https://chatgpt.com"}},
                {"id": "s2", "type": "click_selector", "params": {"selector": "textarea"}},
                {"id": "s3", "type": "type_text", "params": {"text": "Generate a short code snippet with fake API key placeholder."}},
                {"id": "s4", "type": "press_shortcut", "params": {"keys": "enter"}},
                {"id": "s5", "type": "wait", "params": {"seconds": 5}},
                {"id": "s6", "type": "copy_text", "params": {"text": "SIMULATED_BROWSER_AI_OUTPUT_TOKEN_12345"}},
                {"id": "s7", "type": "launch_application", "params": {"app_name": "vscode"}},
                {"id": "s8", "type": "manual_checkpoint", "params": {"instruction": "Focus VS Code editor, then resume for paste simulation.", "timeout_seconds": 900}},
                {"id": "s9", "type": "paste_text", "params": {}},
                {"id": "s10", "type": "assert_clipboard_contains", "params": {"expected": "SIMULATED_BROWSER_AI_OUTPUT_TOKEN"}},
            ],
            ["Clipboard relay from browser to IDE observed"],
            ["clipboard access", "cross-app context movement"],
            ["Potential exfil pathway from web AI output to codebase"],
            ["Clear clipboard", "Close VS Code"],
        ),
        _scenario(
            "scn-upload-file-summary",
            "Upload sample file and request summary",
            "Upload sample text/csv/pdf to browser AI tool and request summary output.",
            "File/Data Transfer Simulations",
            "Upload + Summary",
            ["upload", "summary", "browser", "data-transfer"],
            "critical",
            ["linux", "windows", "darwin"],
            True,
            ["User account for target browser AI tool", "Sample files present"],
            [
                {"id": "s1", "type": "open_website", "params": {"url": "https://chatgpt.com"}},
                {"id": "s2", "type": "manual_checkpoint", "params": {"instruction": "Complete login and open file-upload capable chat.", "timeout_seconds": 1200}},
                {"id": "s3", "type": "upload_file", "params": {"selector": "input[type='file']", "path": "simulator_data/scenarios/samples/sample_brief.txt"}},
                {"id": "s4", "type": "type_text", "params": {"text": "Summarize this file and list sensitive fields."}},
                {"id": "s5", "type": "press_shortcut", "params": {"keys": "enter"}},
                {"id": "s6", "type": "capture_screenshot", "params": {"path": "simulator_data/scenarios/screenshots/upload-summary.png"}},
            ],
            ["File upload action recorded", "Summary request submitted"],
            ["multipart upload", "chat prompt with file context"],
            ["DLP should flag sensitive file transfer to AI domain"],
            ["Delete uploaded chat asset where supported"],
        ),
    ]

    templates_as_scenarios = [
        _scenario(
            "tpl-installation-footprint",
            "Template - Installation footprint test",
            "Template scenario for installer telemetry, artifact, and launch validation.",
            "Desktop AI Apps",
            "Installation Footprint",
            ["template", "installation", "footprint"],
            "medium",
            ["any"],
            False,
            ["Choose target app"],
            [
                {"id": "s1", "type": "install_application", "params": {"app_name": "cursor"}},
                {"id": "s2", "type": "launch_application", "params": {"app_name": "cursor"}},
                {"id": "s3", "type": "capture_screenshot", "params": {}},
            ],
            ["Installer and process telemetry generated"],
            ["download + install event sequence"],
            ["EDR process lineage and package source visibility"],
            ["Stop target app"],
            is_template=True,
        ),
        _scenario(
            "tpl-pre-auth-use",
            "Template - Pre-auth use test",
            "Template for prompt surface checks before account login.",
            "IDE Assistants",
            "Pre-Auth Prompting",
            ["template", "pre-auth"],
            "high",
            ["any"],
            False,
            ["Target app installed"],
            [
                {"id": "s1", "type": "launch_application", "params": {"app_name": "vscode"}},
                {"id": "s2", "type": "manual_checkpoint", "params": {"instruction": "Open assistant panel and verify pre-auth prompt surface."}},
            ],
            ["Pre-auth prompt surface observed"],
            ["UI access path prior to identity controls"],
            ["Should be visible in endpoint interaction telemetry"],
            ["Close app"],
            is_template=True,
        ),
        _scenario(
            "tpl-post-auth-use",
            "Template - Post-auth use test",
            "Template for gated flows that continue after login checkpoint.",
            "Desktop AI Apps",
            "Post-Auth Prompting",
            ["template", "post-auth"],
            "high",
            ["any"],
            True,
            ["Valid account for target service"],
            [
                {"id": "s1", "type": "manual_checkpoint", "params": {"instruction": "Complete login and MFA in target app."}},
                {"id": "s2", "type": "type_text", "params": {"text": "Post-auth prompt simulation"}},
            ],
            ["Post-auth prompt interaction captured"],
            ["Auth success followed by AI usage"],
            ["Identity and usage events should correlate"],
            ["Logout if possible"],
            is_template=True,
        ),
        _scenario(
            "tpl-file-upload",
            "Template - File upload test",
            "Template for uploading sample files into browser AI tools.",
            "File/Data Transfer Simulations",
            "Upload + Summary",
            ["template", "upload"],
            "critical",
            ["any"],
            True,
            ["Authenticated browser AI session"],
            [
                {"id": "s1", "type": "open_website", "params": {"url": "https://chatgpt.com"}},
                {"id": "s2", "type": "upload_file", "params": {"selector": "input[type='file']", "path": "simulator_data/scenarios/samples/sample_metrics.csv"}},
                {"id": "s3", "type": "type_text", "params": {"text": "Summarize uploaded file."}},
            ],
            ["Upload event generated"],
            ["File transfer and prompt metadata"],
            ["DLP and CASB should surface upload"],
            ["Delete uploaded file context"],
            is_template=True,
        ),
        _scenario(
            "tpl-copy-paste-exfil",
            "Template - Copy/paste exfil simulation",
            "Template for clipboard relay from one AI surface to another app.",
            "Cross-App Chained Workflows",
            "Clipboard Relay",
            ["template", "clipboard", "exfil"],
            "critical",
            ["any"],
            False,
            ["Two app contexts available"],
            [
                {"id": "s1", "type": "copy_text", "params": {"text": "SIMULATED_SECRET_VALUE"}},
                {"id": "s2", "type": "paste_text", "params": {}},
                {"id": "s3", "type": "assert_clipboard_contains", "params": {"expected": "SIMULATED_SECRET_VALUE"}},
            ],
            ["Clipboard relay path validated"],
            ["clipboard read/write operations"],
            ["Potential cross-app sensitive movement alert"],
            ["Clear clipboard"],
            is_template=True,
        ),
        _scenario(
            "tpl-mcp-connector",
            "Template - MCP/tool connector test",
            "Template for package install and config injection behavior of MCP connectors.",
            "Agent + MCP Workflows",
            "Connector Provisioning",
            ["template", "mcp"],
            "critical",
            ["any"],
            False,
            ["Node toolchain preferred"],
            [
                {"id": "s1", "type": "mcp_install_server", "params": {"server_id": "filesystem"}},
                {"id": "s2", "type": "mcp_inject_config", "params": {"server_ids": "filesystem"}},
                {"id": "s3", "type": "manual_checkpoint", "params": {"instruction": "Launch AI desktop client and validate MCP server appears in tool list."}},
            ],
            ["MCP package + config modifications"],
            ["npx/pip process plus FIM changes"],
            ["EDR and config integrity detections expected"],
            ["Restore backup config"],
            is_template=True,
        ),
        _scenario(
            "tpl-cross-app-chain",
            "Template - Multi-step cross-app workflow",
            "Template for chaining browser and desktop actions in one run.",
            "Cross-App Chained Workflows",
            "Cross-App Relay",
            ["template", "cross-app"],
            "high",
            ["any"],
            False,
            ["Browser and desktop targets available"],
            [
                {"id": "s1", "type": "open_website", "params": {"url": "https://chatgpt.com"}},
                {"id": "s2", "type": "copy_text", "params": {"text": "CHAINED_OUTPUT"}},
                {"id": "s3", "type": "launch_application", "params": {"app_name": "vscode"}},
                {"id": "s4", "type": "paste_text", "params": {}},
            ],
            ["Cross-app sequence completed"],
            ["browser + desktop + clipboard telemetry"],
            ["Correlated multi-app behavior visible in SIEM"],
            ["Close browser and app"],
            is_template=True,
        ),
        _scenario(
            "tpl-local-model-only",
            "Template - Local-model-only workflow",
            "Template for fully local model runtime prompting.",
            "Local Model Tools",
            "Offline Local Prompting",
            ["template", "local-model"],
            "medium",
            ["any"],
            False,
            ["Local runtime available"],
            [
                {"id": "s1", "type": "install_application", "params": {"app_name": "ollama"}},
                {"id": "s2", "type": "pull_local_model", "params": {"model": "llama3.2:1b"}},
                {"id": "s3", "type": "open_website", "params": {"url": "http://127.0.0.1:11434/api/tags"}},
                {"id": "s4", "type": "assert_text_contains", "params": {"expected": "models"}},
            ],
            ["Local runtime prompt path confirmed"],
            ["Loopback traffic only"],
            ["No cloud egress expected"],
            ["Stop local runtime"],
            is_template=True,
        ),
    ]

    return starter + templates_as_scenarios
